name: 'Action log thien cao'
description: 'A GitHub Action to check for broken links in Markdown files'
author: 'Thien Cao'
inputs:
  message:
    description: 'The message to log'
    required: true
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'link'
  color: 'blue'
